apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/our-velocity-451107-j0/locations/us-central1-c/clusters/cluster-1
  serviceAccount: gke-cicd-svacct@our-velocity-451107-j0.iam.gserviceaccount.com

