apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    serviceAccount: gke-cicd-svacct@our-velocity-451107-j0.iam.gserviceaccount.com
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  - targetId: prod
    serviceAccount: gke-cicd-svacct@our-velocity-451107-j0.iam.gserviceaccount.com
  #   profiles:
  #   - prod